#!/bin/bash
printf "ASMdisk \t Device \t MP DSize \t [Minor Major] \n"
for i in `/etc/init.d/oracleasm listdisks`;
do
        ASMDISK=`/etc/init.d/oracleasm querydisk $i | cut -d\" -f2`
        MINOR=`/etc/init.d/oracleasm querydisk -d $i | tr "[]" " " | awk '{print $NF}' | cut -d, -f1`
        MAJOR=`/etc/init.d/oracleasm querydisk -d $i | tr "[]" " " | awk '{print $NF}' | cut -d, -f2`
        MINOR_C=$MINOR,
        DEVICE=`ls -la /dev |  awk '{print $5, $6, $NF}' | grep $MINOR_C | grep -w $MAJOR | awk '{print $NF}'`
        COUNT_SIZE=`lsblk -o NAME,KNAME,SIZE | grep $DEVICE | awk '{print $(NF)}' | uniq -c`
        printf "$ASMDISK \t /dev/$DEVICE \t $COUNT_SIZE \t [$MINOR $MAJOR] \n";
done
